services:
  - type: web
    name: nexus-ecommerce
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node scripts/initDb.js && node scripts/seedData.js && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: DATABASE_URL
        value: ./database/ecommerce.db
